<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-M1P0KIH" failures="0" tests="17" name="com.mycompany.mavenproject1.TestMavinIT_Organized" time="92.044" errors="2" timestamp="29 Dec 2022 12:58:20 GMT">
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testTabDire" time="3.260"/>
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testSideBarOpen" time="2.177"/>
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testTabLeave" time="3.101"/>
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testTabDashFunc" time="26.646"/>
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testLogout" time="5.136"/>
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testTabAdmin" time="3.330"/>
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testTabDash" time="2.929"/>
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testTabMyInfo" time="4.470"/>
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testTabTime" time="3.230"/>
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testTabBuzz" time="2.858"/>
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testLogin" time="8.691">
    <error message="expected [Paul Collings] but found [Ahmed Abdalkader]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Paul Collings] but found [Ahmed Abdalkader]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.mycompany.mavenproject1.TestMavinIT_Organized.testLogin(TestMavinIT_Organized.java:59)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
    </error>
  </testcase> <!-- testLogin -->
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testTabPerformance" time="4.979"/>
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testLogin" time="8.946">
    <error message="expected [Paul Collings] but found [Ahmed Abdalkader]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Paul Collings] but found [Ahmed Abdalkader]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.mycompany.mavenproject1.TestMavinIT_Organized.testLogin(TestMavinIT_Organized.java:59)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
    </error>
  </testcase> <!-- testLogin -->
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testTabPim" time="3.190"/>
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testSideBarClose" time="2.374"/>
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testTabRecru" time="3.532"/>
  <testcase classname="com.mycompany.mavenproject1.TestMavinIT_Organized" name="testTabMainten" time="3.195"/>
</testsuite> <!-- com.mycompany.mavenproject1.TestMavinIT_Organized -->
